name: to_do_list
description: "Flutter project for SWDV 1011 by Nerizza Jane de Jesus."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  flutter:
    sdk: flutter
  #needed for connecting the app to firestore
  firebase_core: ^2.15.1
  #used for date formatting
  intl: ^0.18.0
  firebase_auth: ^4.19.2
  firebase_ui_auth: ^1.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  #used in displaying calendar in app
  table_calendar: ^3.0.9
  weather: ^3.1.1

flutter:
#material design is the design language for android
  uses-material-design: true
#folder pathway to the app's assets such as images, fonts, etc
  assets:
    - assets/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/Caveat-Regular.ttf
