name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  table_calendar: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/Caveat-Regular.ttf
