// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMPZzPPIWu3Kgj87qcK99gxHOJdUNzUQ',
    appId: '1:417274830005:web:2d5a5215e085bd6765f2fc',
    messagingSenderId: '417274830005',
    projectId: 'to-do-list-9b42f',
    authDomain: 'to-do-list-9b42f.firebaseapp.com',
    storageBucket: 'to-do-list-9b42f.appspot.com',
    measurementId: 'G-HGCPP7EXF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWufLHPFEn5YpbTalPuwsNgT8GRCr0Ys',
    appId: '1:417274830005:android:e735f95423c263a665f2fc',
    messagingSenderId: '417274830005',
    projectId: 'to-do-list-9b42f',
    storageBucket: 'to-do-list-9b42f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCspGaJ8gNagiT0X3NpYixWrJx5a83i1Xc',
    appId: '1:417274830005:ios:86782f4602dcfb2f65f2fc',
    messagingSenderId: '417274830005',
    projectId: 'to-do-list-9b42f',
    storageBucket: 'to-do-list-9b42f.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCspGaJ8gNagiT0X3NpYixWrJx5a83i1Xc',
    appId: '1:417274830005:ios:86782f4602dcfb2f65f2fc',
    messagingSenderId: '417274830005',
    projectId: 'to-do-list-9b42f',
    storageBucket: 'to-do-list-9b42f.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgMPZzPPIWu3Kgj87qcK99gxHOJdUNzUQ',
    appId: '1:417274830005:web:e6bc2a08da72c10a65f2fc',
    messagingSenderId: '417274830005',
    projectId: 'to-do-list-9b42f',
    authDomain: 'to-do-list-9b42f.firebaseapp.com',
    storageBucket: 'to-do-list-9b42f.appspot.com',
    measurementId: 'G-EN6LN17HRH',
  );

}